<?php

namespace ProcessWire;
/**
 * Inputfield 'Image Reference' provides a means for selecting a single image from a predefined page and it's children and/or a folder and/or the page being edited.
 * Per field you can set a page to list from.
 *
 * ©2019 Gerhard Sitzmann
 *
 * ProcessWire 3.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class InputfieldImageReference extends Inputfield implements Module
{

    /**
     * holds all pages with images
     *
     * @var Pages
     */
    protected $imagePages;

    /**
     * Return an array of module information
     *
     * @return array
     */
    public static function getModuleInfo()
    {
        return array(
            'title' => 'Image Reference',
            'version' => 120,
            'summary' => __('Inputfield to select a single image from various sources on the site.'),
            'author' => 'Gerhard Sitzmann',
            'href' => '',
            'requires' => array(
                'FieldtypeImageReference',
                'PHP>=7.1.0',
                'ProcessWire>=3.0.120'
            )
        );
    }

    /**
     * populates properties to inputfield
     *
     * @return void
     */
    public function populateValues()
    {
        // populate field settings data to this input
        foreach($this->wire('fields')->get($this->name)->data as $key => $value) {
            if($key == 'folderpath') $value = trim(trim($value, '/')) . '/';
            $this->set($key, $value);
        }

        // populate imagepages 
        $this->imagePages = $this->getImagePages();
    }

    /**
     * populates config JS
     *
     * @return void
     */
    public function populateConfigJs()
    {
        $input = $this->wire('input');
        if ($this->process == 'ProcessPageEdit') { // we are on a page edit screen
            $editPageUrl = $this->wire('pages')->get($input->id)->editUrl . "&InputfieldImageReference=1";
        } else { // other page 
            $editPageUrl = $this->page->url . "?InputfieldImageReference=1";
        }
        $this->wire('config')->js($this->className, array(
            'url' => $editPageUrl
        ));
    }

    /**
     * Set an attribute to this Inputfield
     *
     * In this case, we just capture the 'value' attribute and make sure it's something valid
     * 
     * @param string $key
     * @param mixed $value
     * @return $this
     *
     */
    public function setAttribute($key, $value)
    {
        if ($key == 'value' && empty($value)) {
            $value = FieldtypeImageReference::toJson();
        }

        return parent::setAttribute($key, $value);
    }

    public function isEmpty()
    {
        return (!$this->value);
    }

    /**
     * Return the completed output of Inputfield select file
     *
     * @return string
     *
     */
    public function ___render()
    {
        $this->populateValues();
        $this->populateConfigJs();
        $input = $this->wire('input');

        // render thumbnails only for ajax request
        if ($input->InputfieldImageReference && isset($input->pageid)) {
            if((int) $input->pageid === 0) {
                echo $this->getThumbnailsForFolder($this->folderpath);
            } else {
                echo $this->getThumbnailsForPage($input->pageid);
            }
            exit;
        }

        $name = $this->attr('name');
        $value = json_decode($this->attr('value'));
        if ($value->pageid === -1) {
            $message = $this->_("The referenced image was deleted. Choose a new image");
            $this->page->error($this->_("The referenced image was deleted. Choose a new image"));
            $this->error($message);
        }
        $out = $this->renderSelectedImage($value);
        $out .= $this->renderInputs($name, $value);
        $out .= $this->renderThumbnails();

        return $out;
    }

    public function renderSelectedImage($value)
    {
        $previewWidth = ($this->previewWidth) ? $this->previewWidth : 200;
        $blankSrc = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mN89x8AAuEB74Y0o2cAAAAASUVORK5CYII=';
        $image = $this->getImage($value);
        $url = ($image) ? $image->width($previewWidth)->url : $blankSrc;
        $info = ($image) ? $this->renderTooltip($image) : '';
        $out = "<div class='uk-panel uk-panel-box uk-margin-bottom'>
        <span class='fa fa-trash' uk-tooltip='title: Remove Image'></span>
        <img src='{$url}' style='width: {$previewWidth}px; max-width: {$previewWidth}px' data-src='{$blankSrc}'>
        <div class='uk-thumbnail-caption' style='max-width: {$previewWidth}px'>{$info}</div>";
        $out .= "</div>";

        return $out;
    }

    public function renderInputs($name, $value)
    {
        $value = FieldtypeImageReference::toJson($value->pageid, $value->filename);
        return "<div>
        <input type='hidden' class='imagereference_value' name='{$name}' id='{$name}' value='{$value}' \>
        </div>";
    }

    public function renderThumbnails()
    {
        $wrapper = new InputfieldWrapper;
        $wrapper->attr('id', 'imagereference_thumbs');
        foreach ($this->imagePages as $p) $wrapper->add($this->renderThumbnailsForPage($p));
        if($this->fromfolder && $this->folderpath) $wrapper->add($this->renderThumbnailsForFolder($this->folderpath));
        if($this->anypage) $wrapper->add($this->pickFromAnyPage());

        /**
         * @todo: add pick image from any page.
         * make use of ProcessPageEditImageSelect
         * retrieve page picker an thumbs with URL like /adminUrl/page/image/?id=1119&edit_page_id=1001&modal=1&field=images 
         */
        
        return $wrapper->render();
    }

    /**
     * renders thumbnails for an image page inside an InputfieldMarkup
     *
     * @param Page $page
     * @return InputfieldMarkup inputfield markup instance
     */
    public function renderThumbnailsForPage($page)
    {
        $imageFields = $this->getImageFields($page);
		if(count($imageFields)) {
			$imageFieldNames = implode(',', array_keys($imageFields)); 
			/** @var InputfieldButton $btn */
			$btn = $this->modules->get('InputfieldButton');
			// $uploadOnlyMode = "$this->page" === "$this->editorPage" ? 1 : 2;
			$btn->href = "{$page->editUrl}&modal=1&fields={$imageFieldNames}&from=imagereference";
			$btn->value = $this->_('Upload Image');
			$btn->addClass('imagereference_editimages pw-modal pw-modal-button pw-modal-button-visible'); 
			$btn->icon = 'upload';
			// $changes = $this->wire('input')->get('changes'); 
			// if($changes) foreach(explode(',', $changes) as $name) {
			// 	$name = $this->wire('sanitizer')->fieldName($name); 
			// 	$field = $this->wire('fields')->get($name); 
			// 	if(!$field) continue;
			// 	$out .= "<script>refreshPageEditField('$name');</script>";
			// }
            // $button = $btn->render();
            $button = "<a href='{$page->editUrl}&fields={$imageFieldNames}&from=imagereference' class='imagereference_editimages pw-modal' title='" . $this->_('Upload Images') . "' uk-tooltip data-buttons='button#submit_save' data-autoclose><i class='fa fa-upload'></i></a>";
		}

        $markup = '<ul class="uk-thumbnav uk-grid-width-1-6" data-pageid="' . $page->id . '">';
        if (!$this->useajax) $markup .= $this->getThumbnailsForPage($page->id);
        $markup .= '</ul>';
        $markupField = new InputfieldMarkup; // $this->wire('modules')->get('InputfieldMarkup');
        $markupField->class('imagereference_thumbholder');
        $markupField->id = "imagereference_  thumbs_{$page->id}";
        // $markupField->attr('data-pageid', $page->id); // does not work
        $markupField->label = sprintf($this->_('Choose an image from page "%s"'), $page->title);
        $markupField->entityEncodeLabel = false;
        $markupField->markupText = $button . $markup;
        $markupField->collapsed(1); 

        return $markupField;
    }

    /**
     * renders thumbnails for images in a folder inside an InputfieldMarkup
     *
     * @param string $folderpath
     * @return InputfieldMarkup inputfield markup instance
     */
    public function renderThumbnailsForFolder($folderpath)
    {

        $markup = '<ul class="uk-thumbnav uk-grid-width-1-6" data-pageid="0">';
        if (!$this->useajax) $markup .= $this->getThumbnailsForFolder($folderpath);
        $markup .= '</ul>';
        $markupField = new InputfieldMarkup; // $this->wire('modules')->get('InputfieldMarkup');
        $markupField->class('imagereference_thumbholder');
        // $markupField->attr('data-pageid', $page->id); // does not work
        $markupField->label = sprintf($this->_('Choose an image from folder "%s"'), $folderpath);;
        $markupField->entityEncodeLabel = false;
        $markupField->markupText = $markup;
        $markupField->collapsed(1); 

        return $markupField;
    }

    /**
     * lets user select a page and
     * renders thumbnails for that page a InputfieldWrapper
     *
     * @param Page $page
     * @return InputfieldWrapper inputfield wrapper instance
     */
    public function pickFromAnyPage()
    {
        // set initial value of PageListSelect
        $value = 0;
        $pageid = (int) wireDecodeJSON($this->attr('value'))['pageid'];
        if( // pageid of stored image is not thet of editPage or one of the imagepages
            ($pageid !== 0)
            && ($this->frompage && $this->hasPage && $this->hasPage->id != $pageid)
            && (!$this->imagePages->has($this->wire('pages')->get($pageid)))
        ) $value = $pageid;    

        
        $wrapper = new InputfieldWrapper;
        /** @var InputfieldPageListSelect $field */
		$field = $this->modules->get("InputfieldPageListSelect"); 
        $field->label = $this->_("Choose any page to get images from");
        $field->startLabel = $this->_("Choose a page");
        $field->showPath = false;
        $field->description = ($value) 
        ? $this->_("If you would like to select images from any page, select the page below.") 
        : $this->_("If you would like to select images from a different page, select the page below.");
		$field->attr('id+name', 'anypage'); 
		if($value) $field->value = $value; 
        $field->parent_id = 0; 
		$field->collapsed = Inputfield::collapsedYes;
        $wrapper->add($field);

        $markup = '<ul class="uk-thumbnav uk-grid-width-1-6" data-pageid="">';
        if ($value) $markup .= $this->getThumbnailsForPage($pageid);
        $markup .= '</ul>';
        $markupField = new InputfieldMarkup; 
        $markupField->class('imagereference_thumbholder');
        $markupField->id = "imagereference_thumbs_anypage";
        $pageName = ($value) ? $this->wire->pages($pageid)->title : '';
        $markupField->label = $this->_('Choose an image from page') . " \"<span id='imagereference_anypage_pagename'>{$pageName}</span>\"";
        // $markupField->skipLabel = Inputfield::skipLabelHeader;
        $markupField->entityEncodeLabel = false;
        $markupField->markupText = $markup;
        // $markupField->collapsed(1);
        $markupField->showIf('anypage!=""');
        $wrapper->add($markupField);
        return $wrapper; 
    }

    /**
     * renders thumbnails markup for an image page
     *
     * @param int $pageid
     * @return string thumbnail markup for page images
     */
    public function getThumbnailsForPage($pageid)
    {
        $page = $this->wire('pages')->get($pageid);
        $images = $this->getPageImages($page);
        if (!$images->count) {
            $imageFields = $this->getImageFields($page);
            $imageFieldNames = implode(',', array_keys($imageFields));
            $markup = '<b>' . $this->_('There are no images. You first need to upload images to page') .  $page->title . '</b>';
        } else {
            $thumbWidth = ($this->thumbWidth) ? $this->thumbWidth : 100;
            $markup = '';
            foreach ($images as $img) {
                $tooltip = $this->renderTooltip($img);
                $markup .= "<li class='uk-thumbnail uk-thumbnail-mini'>
                <img style='max-width: {$thumbWidth}px; width: {$thumbWidth}px' data-pageid='{$page->id}' data-filename='{$img->basename}' src='{$img->width($thumbWidth)->url}' alt='{$img->basename}'  uk-tooltip title='{$tooltip}'>
                </li>";
            }
        }

        return $markup;
    }

    /**
     * renders thumbnails markup for images in a folder
     *
     * @param int $page
     * @return string thumbnail markup for folder images
     */
    public function getThumbnailsForFolder($folderpath)
    {
        $baseUrl = $this->wire('config')->urls->templates . $folderpath;
        $images = FieldtypeImageReference::getPageimages($folderpath);

        if (!$images->count) {
            $markup = '<b>' . $this->_('There are no images. Upload images to folder') . ' ' . $baseUrl . '</b>';
        } else {
            $thumbWidth = ($this->thumbWidth) ? $this->thumbWidth : 100;
            $markup = '';
            foreach ($images as $img) {
                $tooltip = $this->renderTooltip($img);
                $markup .= "<li class='uk-thumbnail uk-thumbnail-mini'>
                <img style='max-width: {$thumbWidth}px; width: {$thumbWidth}px' data-pageid='0' data-filename='{$img->basename}' src='{$img->width($thumbWidth)->url}' alt='{$img->basename}'  uk-tooltip title='{$tooltip}'>
                </li>";
            }
        }

        return $markup;
    }

    /**
     * creates tooltip markup
     * @param mixed $img Pageimage|string|null either a Pageimage object, filename string or null
     */
    public function renderTooltip($img)
    {
        if(is_null($img)) return '';
        $out = $img->basename;
        if ($img->description) $out .= '<br>' . $img->description;
        $out .= '<br>' . $img->filesizeStr;
        if (strtolower($img->ext) !== 'svg') $out .= '<br>' . "{$img->width} x {$img->height} px";
        if(!$img->page instanceof ImageReferenceVirtualpage) $out .= '<br>' . $this->_('Page:') . ' ' . $img->page->title;
        if($img->page instanceof ImageReferenceVirtualpage) $out .= '<br>' . $this->_('Folder:') . ' ' . $this->folderpath;
        if($img->field && $img->field->name != 'imagereferencevirtualfield') $out .= '<br>' . $this->_('Field:') . ' ' . $img->field->name;

        return $out;
    }

	/**
	 * Get all editable image fields on the page that are allowed image fields
	 * 
	 * @param Page $page
	 * @param bool $excludeFullFields Exclude fields that are already full? (i.e. can't add more images to them)
	 * @return array of Field objects for image fields
	 * 
	 */
	public function getImageFields(Page $page, $excludeFullFields = true) {
        
		$imageFields = array();

		foreach($page->fields as $field) {
            if(!$field->type instanceof FieldtypeImage) continue;
            if(!in_array($field->name, $this->imagesfields)) continue;
			if(!$page->editable($field->name)) continue; 
			if($excludeFullFields && $field->maxFiles > 0) {
				if(count($page->get($field->name)) >= $field->maxFiles) continue; 
			}
			$imageFields[$field->name] = $field;
        }
		return $imageFields; 
	}

    /**
     * gets all pages that serve image thumbnails to the inputfield
     *
     * @return PageArray might be empty, depending on options chosen for the field
     */
    public function getImagePages()
    {
        $pages = new PageArray;
        
        // parent and children of chosen page
        if($this->frompages && $this->imagespage) {
            $p = $this->wire('pages')->get($this->imagespage, array('include' => 'hidden'));
            if($p->id) {
                $imageFields = $this->getImageFields($p);
                if(!empty($imageFields)) {
                    $pages->add($p);
                }
                if ($this->includechildren) {
                    foreach ($pages->first()->children('include=hidden') as $child) {
                        $imageFields = $this->getImageFields($child);
                        if (!empty($imageFields)) $pages->add($child);
                    }
                }

            }
        }
        // editPage: page the field lives on
        if($this->frompage && $this->hasPage && !empty($this->getImageFields($this->hasPage))) $pages->add($this->hasPage);
        return $pages;
    }

    /**
     * gets all images from all imagefields on a page
     *
     * @param Page $page
     * @return Pageimages
     */
    public function getPageImages($page)
    {
        $imagefields = ($this->frompage && $page == $this->hasPage) ? $this->getImageFields($this->hasPage) : $this->getImageFields($page);
        $images =  new Pageimages($page);
        foreach ($imagefields as $field) {
            foreach ($page->get($field->name) as $pageimage) $images->add($pageimage);
        }
        return $images;
    }

    /**
     * gets the image from stored page id and filename
     *
     * @param object $value holds $value->pageid and $value->filename
     * @return mixed Pageimage|null
     */
    public function getImage($value) {
        if ($value->pageid && $value->filename) {
            // get image from imagespage or editPage
            $imagefields = array();
            if ($this->frompage && $this->hasPage && ($value->pageid == $this->hasPage->id)) { // get image from editPage
                $imagefields = $this->getImageFields($this->hasPage);
            } else { // get image from imagespage
                $imagefields = $this->getImageFields($this->pages->get($value->pageid));
            } 
            $image = null;
            $page = $this->wire('pages')->get($value->pageid);
            if($page->id) {
                foreach ($imagefields as $field) {
                    if ($image = $page->get($field->name)->getFile($value->filename)) break;
                }
            }
        } elseif ((int) $value->pageid === 0 && $value->filename) {
            // get image from folder
            $images = FieldtypeImageReference::getPageimages($this->folderpath);
            $image = $images->getFile($value->filename);
        } elseif ((int) $value->pageid === 0 && empty($value->filename)) {
            // empty image
            $image = null;
        }
        if(is_null($image) && !empty($value->filename)) {
            $location = ((int) $value->pageid === 0) ? "folder {$this->folderpath}" : "page {$page->title}";
            $this->error(sprintf($this->_('The saved image %1$s from %2$s cannot be found'), $value->filename, $location));
        }

        return $image;

    }

    /**
     * Process the input after a form submission
     * 
     * @param WireInputData $input
     * @return $this
     *
     */
    public function ___processInput(WireInputData $input)
    {
        $name = $this->attr('name');
        $value = $this->attr('value');
        $valueObj = json_decode($value);
        $newValue = json_decode($input[$name]);
        if (!isset($newValue->filename) && !isset($newValue->pageid)) $newValue = json_decode(FieldtypeImageReference::toJson());
       
        $filename = $newValue->filename;
        $pageid = $newValue->pageid;
        if($valueObj->filename == $filename && $valueObj->pageid == $pageid) return $this;

        $this->attr('value', json_encode($newValue));

        $page = ($this->hasPage) ? $this->hasPage : $this->page;
        $page->set($name, $this->attr('value'));

        return $this;
    }
}
